const icons = { home:"⌂",work:"✓",more:"•••",search:"⌕",filter:"▽",sort:"⇅",group:"▤",settings:"⚙",plus:"+",close:"×",export:"⇩",import:"⇧",trash:"⌫",menu:"☰",chevron:"⌄",edit:"✎",board:"▧",people:"◎",copy:"▣" };
const icon = (name) => `<span class="icon" aria-hidden="true">${icons[name] || name}</span>`;

class AppView {
  constructor(root) { this.root = root; }
  applyDisplay(model) {
    const systemDark = typeof matchMedia === "function" && matchMedia("(prefers-color-scheme: dark)").matches;
    document.documentElement.dataset.theme = model.settings.theme === "system" ? (systemDark ? "dark" : "light") : model.settings.theme;
    document.documentElement.dataset.fontSize = model.settings.fontSize;
    document.documentElement.dataset.contrast = model.settings.highContrast ? "high" : "normal";
    document.documentElement.dataset.motion = model.settings.reduceMotion ? "reduced" : "normal";
    document.documentElement.dataset.stickyColumn = model.settings.stickyFirstColumn ? "on" : "off";
    document.documentElement.style.setProperty("--accent", model.settings.accentColor);
    document.documentElement.style.setProperty("--focus", model.settings.accentColor);
  }
  render(model) {
    this.applyDisplay(model);
    document.documentElement.dataset.density = model.settings.density;
    this.root.innerHTML = `<div class="app-shell">${this.sidebar(model)}<main class="workspace">${this.topbar(model)}${this.content(model)}</main></div><input id="import-file" class="sr-only" type="file" accept="application/json,.json,text/csv,.csv" data-action="import-file"><input id="avatar-file" class="sr-only" type="file" accept="image/png,image/jpeg,image/webp" data-action="avatar-file"><div id="overlay-root"></div>`;
  }

  renderLogin(auth, model) {
    this.applyDisplay(model);
    const lastLogin = auth.lastLogin ? this.time(auth.lastLogin) : "First sign-in";
    this.root.innerHTML = `<main class="login-shell"><section class="login-brand-panel"><div class="login-brand"><span class="brand-mark">M</span><div><strong>Medtek</strong><small>Operations Database</small></div></div><div class="login-context"><div class="eyebrow">Secure local workspace</div><h1>Work stays organized.</h1><p>Manage boards, records, assignments, notifications, and personal views in one focused workspace.</p><div class="login-signals"><span><i></i> Local autosave</span><span><i></i> Session protection</span><span><i></i> Adaptive display settings</span></div></div><small class="login-version">Medtek Database · Version 7</small></section><section class="login-panel"><form class="login-form" data-action="login-form" novalidate><div class="login-mobile-brand"><span class="brand-mark">M</span><strong>Medtek</strong></div><div class="eyebrow">${auth.lockedScreen ? "Workspace locked" : "Welcome back"}</div><h2>${auth.lockedScreen ? "Unlock Medtek" : "Sign in to Medtek"}</h2><p>${auth.lockedScreen ? "Enter your credentials to continue where you left off." : "Use your workspace account to continue."}</p>${auth.error ? `<div class="login-error" role="alert">${this.escape(auth.error)}</div>` : ""}<label>Username<input name="username" autocomplete="username" required value="${this.escape(auth.rememberedUsername)}" placeholder="Enter username" autofocus></label><label>Password<div class="password-field"><input name="password" type="password" autocomplete="current-password" required placeholder="Enter password" data-action="password-input"><button type="button" data-action="toggle-password" aria-label="Show password">Show</button></div><small id="caps-warning" class="caps-warning" hidden>Caps Lock is on</small></label><div class="login-options"><label><input type="checkbox" name="rememberUsername" ${auth.rememberedUsername ? "checked" : ""}> Remember username</label><label><input type="checkbox" name="rememberSession"> Keep me signed in</label></div><button class="button primary login-submit" type="submit">${auth.lockedScreen ? "Unlock workspace" : "Sign in"}</button><div class="demo-access"><strong>Prototype access</strong><span>Username: <code>medtek</code></span><span>Password: <code>123</code></span></div><small class="last-login">Last login: ${lastLogin}</small></form></section></main>`;
  }

  sidebar(model) {
    return `<aside class="sidebar" id="sidebar"><div class="brand" data-tooltip="Medtek"><span class="brand-mark">M</span><div><strong>Medtek</strong><small>Operations Database</small></div></div><nav aria-label="Primary navigation">
      <button class="nav-item ${model.screen === "home" ? "active" : ""}" data-action="nav" data-screen="home" data-tooltip="Home">${icon("home")}<span class="nav-text">Home</span></button>
      <button class="nav-item ${model.screen === "mywork" ? "active" : ""}" data-action="nav" data-screen="mywork" data-tooltip="My work">${icon("work")}<span class="nav-text">My work</span><span class="nav-count">${model.myWork.length}</span></button>
      <button class="nav-item" data-action="more-menu" data-tooltip="More">${icon("more")}<span class="nav-text">More</span></button>
      <div class="workspace-heading"><p class="nav-label">Workspace</p><button class="mini-button" data-action="new-board" aria-label="Create board">+</button></div>
      <button class="workspace-switch" data-action="workspace-menu" data-tooltip="${this.escape(model.workspace.name)}"><span class="workspace-icon" style="background:${model.workspace.color}">${model.workspace.name[0]}</span><span class="workspace-name">${this.escape(model.workspace.name)}</span>${icon("chevron")}</button>
      <div class="nav-tree">${model.workspace.boards.map((board) => `<div class="board-nav ${model.screen === "board" && model.currentBoardId === board.id ? "selected" : ""}"><button class="tree-item" data-action="open-board" data-id="${board.id}" data-tooltip="${this.escape(board.name)}"><span class="tree-icon">${board.icon}</span><span class="nav-text">${this.escape(board.name)}</span>${board.favorite ? '<span class="favorite-indicator">★</span>' : ""}</button><button class="board-menu-button" data-action="board-menu" data-id="${board.id}" aria-label="Board options">•••</button></div>`).join("")}</div>
    </nav><div class="sidebar-footer"><span class="presence-dot"></span><span>Saved locally</span><button data-action="collapse-nav" aria-label="Collapse sidebar">‹</button></div></aside>`;
  }

  topbar(model) {
    const avatar = model.profile.avatar ? `<img src="${model.profile.avatar}" alt="">` : this.escape(model.profile.initials);
    return `<header class="topbar"><div class="top-context"><button class="icon-button mobile-only" data-action="toggle-nav" aria-label="Open navigation">${icon("menu")}</button><span class="enterprise">Enterprise</span></div><div class="top-actions"><span class="save-state"><i></i> Saved ${new Intl.DateTimeFormat("en",{hour:"numeric",minute:"2-digit"}).format(new Date())}</span><button class="icon-button" data-action="command-palette" aria-label="Open command palette" title="Command palette (Ctrl+K)">${icon("search")}</button><button class="notification-button" data-action="notifications" aria-label="Notifications">♧${model.unreadCount ? `<b>${model.unreadCount > 9 ? "9+" : model.unreadCount}</b>` : ""}</button><button class="invite-button" data-action="invite">${icon("people")} Invite</button><button class="settings-button" data-action="settings">${icon("settings")} <span>Settings</span><small>${this.cap(model.settings.theme)}</small></button><button class="profile profile-button" data-action="profile-menu" style="background:${model.profile.color}" aria-label="Open profile">${avatar}<i class="presence presence-${model.profile.presence.toLowerCase()}"></i></button></div></header>`;
  }

  content(model) {
    if (model.screen === "home") return this.home(model);
    if (model.screen === "mywork") return this.myWork(model);
    return this.boardScreen(model);
  }

  home(model) {
    const total = model.workspace.boards.reduce((sum, board) => sum + board.records.length, 0);
    return `<section class="page-head"><div><div class="eyebrow">${this.escape(model.workspace.name)} workspace</div><h1>Welcome, ${this.escape(model.profile.name.split(" ")[0])}</h1><p>Open a board or create a new workflow.</p></div><button class="button primary" data-action="new-board">${icon("plus")} New board</button></section><section class="workspace-summary"><div><span>Boards</span><strong>${model.workspace.boards.length}</strong></div><div><span>Total records</span><strong>${total}</strong></div><div><span>Assigned to me</span><strong>${model.myWork.filter((record) => record.workspaceId === model.workspace.id).length}</strong></div></section>${model.favoriteBoards.length ? this.boardStrip("Favorites",model.favoriteBoards) : ""}${model.recentBoardItems.length ? this.boardStrip("Recent boards",model.recentBoardItems) : ""}<section class="boards-section"><div class="section-heading"><h2>Your boards</h2><button data-action="new-board">${icon("plus")} Add board</button></div><div class="board-grid">${model.workspace.boards.map((board) => `<article class="board-tile"><button data-action="open-board" data-id="${board.id}"><span class="board-tile-icon">${board.icon}</span><span><strong>${this.escape(board.name)}</strong><small>${board.records.length} records · ${board.activity.length} updates</small></span><b>→</b></button></article>`).join("")}</div></section>`;
  }
  boardStrip(title, boards) { return `<section class="board-strip"><div class="section-heading"><h2>${title}</h2></div><div>${boards.map((board) => `<button data-action="open-record-board" data-board="${board.id}" data-workspace="${board.workspaceId}"><span>${board.icon}</span><strong>${this.escape(board.name)}</strong><small>${this.escape(board.workspaceName || "")}</small></button>`).join("")}</div></section>`; }

  myWork(model) {
    const rows = model.myWork;
    return `<section class="page-head"><div><div class="eyebrow">Assigned to ${this.escape(model.profile.initials)}</div><h1>My work</h1><p>Items assigned to you across every workspace and board.</p></div></section><section class="data-region"><div class="group-title"><span class="status-dot landing"></span>Assigned items <small>${rows.length}</small></div>${rows.length ? this.crossBoardTable(rows) : this.blank("work", "Nothing assigned yet", `Choose ${this.escape(model.profile.initials)} as the owner of a record and it will appear here.`)}</section>`;
  }

  boardScreen(model) {
    return `<section class="board-head"><div class="title-row"><div><div class="eyebrow">Board</div><h1>${this.escape(model.board.name)} <span>v7</span></h1><button class="board-description" data-action="edit-description">${this.escape(model.board.description || "Add a board description")}</button></div><div class="board-actions"><button class="favorite-button ${model.board.favorite ? "active" : ""}" data-action="toggle-favorite" aria-label="Favorite board">★</button><button class="button secondary" data-action="import">${icon("import")} Import</button><button class="button secondary" data-action="export" ${model.rows.length ? "" : "disabled"}>${icon("export")} Export</button><button class="button primary" data-action="open-form">${icon("plus")} New record</button></div></div>${this.tabs(model)}</section>${model.currentView === "table" ? this.toolbar(model) : ""}${model.selected.size ? this.bulkBar(model) : ""}${this.boardView(model)}`;
  }

  tabs(model) {
    return `<div class="tabs" role="tablist">${[["table","Main table"],["kanban","Kanban"],["activity","Activity"]].map(([id,label]) => `<button role="tab" data-action="view" data-view="${id}" class="${model.currentView === id ? "active" : ""}">${label}${id === "kanban" ? `<span class="count">${model.rows.length}</span>` : ""}</button>`).join("")}<button data-action="new-view" aria-label="Add view">+</button></div>`;
  }

  toolbar(model) {
    return `<section class="board-tools"><label class="search-field">${icon("search")}<input id="board-search" data-action="search" value="${this.escape(model.query)}" placeholder="Search this board..."><kbd>/</kbd></label><label class="select-control">${icon("filter")}<select data-action="filter">${["All","Clear","Review","Defective"].map((status) => `<option ${model.status === status ? "selected" : ""}>${status}</option>`).join("")}</select></label><button class="tool-button" data-action="sort">${icon("sort")} ${model.sortDirection === "desc" ? "Newest" : "Oldest"}</button><button class="tool-button ${model.grouped ? "active" : ""}" data-action="group">${icon("group")} Group</button><button class="tool-button" data-action="saved-views">Saved views</button><button class="tool-button" data-action="manage-groups">Groups</button><button class="tool-button" data-action="manage-columns">Columns</button><button class="tool-button" data-action="undo" ${model.canUndo ? "" : "disabled"}>↶ Undo</button><button class="tool-button accent-tool" data-action="quick-add">+ Quick add</button><span class="result-count">${model.visibleRows.length} of ${model.rows.length}</span></section>`;
  }

  bulkBar(model) { return `<div class="bulk-bar"><strong>${model.selected.size} selected</strong><button data-action="bulk-status">Set status</button><button data-action="bulk-owner">Assign owner</button><button data-action="bulk-priority">Set priority</button><button data-action="delete-selected">${icon("trash")} Delete</button><button data-action="clear-selection">Clear</button></div>`; }
  boardView(model) {
    if (model.currentView === "kanban") return this.kanban(model);
    if (model.currentView === "activity") return this.activity(model);
    if (!model.rows.length) return this.blank("board", "This board is ready", "Add a record to start tracking work on this board.", true);
    const rows = model.visibleRows;
    if (!rows.length) return this.blank("search", "No matching records", "Adjust the search or status filter.");
    if (model.grouped) return `<section class="data-region grouped">${model.board.groups.map((group) => { const items = rows.filter((row) => row.group === group); return items.length ? `<div class="group"><div class="group-title"><span class="group-marker"></span>${this.escape(group)}<small>${items.length}</small></div>${this.table(items, model)}</div>` : ""; }).join("")}</section>`;
    return `<section class="data-region"><div class="group-title"><span class="group-marker group-new"></span>All records <small>${rows.length}</small></div>${this.table(rows, model)}</section>`;
  }

  table(rows, model) {
    return `<div class="table-wrap"><table class="editable-table"><thead><tr><th class="check-col"><input type="checkbox" data-action="select-all" ${rows.every((row) => model.selected.has(row.id)) ? "checked" : ""}></th>${model.visibleColumns.map((column) => `<th data-column-key="${column.key}"><span>${column.label}</span>${model.board.columnConfig[column.key].connection ? '<i class="connected-dot" title="Connection configured"></i>' : ""}</th>`).join("")}<th class="actions-col">Actions</th></tr></thead><tbody>${rows.map((row) => this.row(row, model)).join("")}<tr class="quick-add-row"><td></td><td colspan="${model.visibleColumns.length + 1}"><button data-action="quick-add">+ Add record directly to this board</button></td></tr></tbody></table></div>`;
  }
  row(row, model) {
    return `<tr class="${model.selected.has(row.id) ? "is-selected" : ""}"><td class="check-col"><input type="checkbox" data-action="select" data-id="${row.id}" ${model.selected.has(row.id) ? "checked" : ""}></td>${model.visibleColumns.map((column) => `<td data-column-key="${column.key}">${this.cellEditor(row,column,model)}</td>`).join("")}<td class="row-actions"><button class="icon-button" data-action="duplicate-record" data-id="${row.id}" title="Duplicate">${icon("copy")}</button><button class="icon-button" data-action="edit" data-id="${row.id}" title="Open full editor">${icon("edit")}</button><button class="icon-button danger" data-action="delete" data-id="${row.id}" title="Delete">${icon("trash")}</button></td></tr>`;
  }

  cellEditor(row, column, model) {
    const attrs = `data-action="cell-edit" data-id="${row.id}" data-field="${column.key}" data-column-key="${column.key}" aria-label="Edit ${column.label}"`;
    if (column.type === "group") return `<select class="inline-editor" ${attrs}>${model.board.groups.map((value) => `<option ${row.group === value ? "selected" : ""}>${this.escape(value)}</option>`).join("")}</select>`;
    if (column.type === "owner") return `<select class="inline-editor" ${attrs}>${["Unassigned",model.profile.initials,"Engineering","QA Team"].map((value) => `<option ${row.owner === value ? "selected" : ""}>${value}</option>`).join("")}</select>`;
    if (column.type === "status") return `<select class="inline-editor status-editor status-${row.status.toLowerCase()}" ${attrs}>${["Review","Defective","Clear"].map((value) => `<option ${row.status === value ? "selected" : ""}>${value}</option>`).join("")}</select>`;
    if (column.type === "priority") return `<select class="inline-editor priority-editor" ${attrs}>${["Low","Medium","High","Critical"].map((value) => `<option ${row.priority === value ? "selected" : ""}>${value}</option>`).join("")}</select>`;
    return `<input class="inline-editor" ${attrs} type="${column.type === "date" ? "date" : "text"}" value="${this.escape(row[column.key] || "")}" ${column.required ? "required" : ""} placeholder="${column.type === "date" ? "" : "Add value"}">`;
  }

  kanban(model) {
    return `<section class="kanban">${["Review","Defective","Clear"].map((status) => { const items = model.rows.filter((row) => row.status === status); return `<div class="kanban-column"><div class="kanban-head"><span class="status-dot ${status.toLowerCase()}"></span><strong>${status}</strong><small>${items.length}</small></div><div class="kanban-list">${items.map((row) => `<article class="kanban-card"><button data-action="edit" data-id="${row.id}"><strong>${this.escape(row.serial)}</strong><span>${this.escape(row.group)} · ${this.escape(row.priority)}</span><small>${row.owner === "M" ? '<b class="owner">M</b>' : "Unassigned"} ${this.date(row.dueDate)}</small></button><div class="kanban-move">${["Review","Defective","Clear"].filter((value) => value !== status).map((value) => `<button data-action="move-status" data-id="${row.id}" data-status="${value}">Move to ${value}</button>`).join("")}</div></article>`).join("") || `<div class="kanban-empty">No items</div>`}</div><button class="kanban-add" data-action="open-form" data-status="${status}">+ Add item</button></div>`; }).join("")}</section>`;
  }

  activity(model) {
    return `<section class="activity-view"><div class="section-heading"><div><h2>Board activity</h2><p>Local changes made to this board.</p></div></div><div class="activity-list">${model.board.activity.length ? model.board.activity.map((entry) => `<div class="activity-item"><span class="profile small">M</span><div><strong>${this.escape(entry.text)}</strong><small>${this.time(entry.at)}</small></div></div>`).join("") : this.blank("activity", "No activity yet", "Changes to this board will appear here.")}</div></section>`;
  }

  crossBoardTable(rows) { return `<div class="table-wrap"><table><thead><tr><th>Record</th><th>Board</th><th>Workspace</th><th>Status</th><th>Priority</th><th>Due</th></tr></thead><tbody>${rows.map((row) => `<tr><td><button class="link-button" data-action="open-record-board" data-board="${row.boardId}" data-workspace="${row.workspaceId}">${this.escape(row.serial)}</button></td><td>${this.escape(row.boardName)}</td><td>${this.escape(this.workspaceName(row.workspaceId))}</td><td><span class="status status-${row.status.toLowerCase()}">${row.status}</span></td><td>${row.priority}</td><td>${this.date(row.dueDate)}</td></tr>`).join("")}</tbody></table></div>`; }
  workspaceName(id) { return id === "engineering" ? "Engineering" : "Operations"; }
  blank(type, title, text, action = false) { return `<section class="empty-state ${type}"><div class="empty-visual"><span></span><span></span><span></span></div><div class="eyebrow">Blank view</div><h2>${title}</h2><p>${text}</p>${action ? `<button class="button primary" data-action="open-form">${icon("plus")} New record</button>` : ""}</section>`; }

  showForm(record = {}, presetStatus = "Review", model) {
    const today = new Date().toISOString().slice(0,10);
    document.querySelector("#overlay-root").innerHTML = `<div class="overlay" data-action="close-overlay"><form class="modal" id="record-form" data-action="record-form"><div class="modal-head"><div><div class="eyebrow">Board item</div><h2>${record.id ? "Edit record" : "New record"}</h2></div><button type="button" class="icon-button" data-action="close-overlay">${icon("close")}</button></div><input type="hidden" name="id" value="${record.id || ""}"><div class="form-grid"><label class="full">Record / Serial <input name="serial" required maxlength="80" value="${this.escape(record.serial || "")}" placeholder="MEDTEK-2026-001"></label><label>Group <select name="group">${model.board.groups.map((v) => `<option ${record.group === v ? "selected" : ""}>${this.escape(v)}</option>`).join("")}</select></label><label>Status <select name="status">${["Review","Defective","Clear"].map((v) => `<option ${(record.status || presetStatus) === v ? "selected" : ""}>${v}</option>`).join("")}</select></label><label>Owner <select name="owner">${["Unassigned","M","Engineering","QA Team"].map((v) => `<option ${record.owner === v ? "selected" : ""}>${v}</option>`).join("")}</select></label><label>Priority <select name="priority">${["Low","Medium","High","Critical"].map((v) => `<option ${(record.priority || "Medium") === v ? "selected" : ""}>${v}</option>`).join("")}</select></label><label>Date received <input name="received" type="date" required value="${record.received || today}"></label><label>Due date <input name="dueDate" type="date" value="${record.dueDate || ""}"></label><label>RR / Invoice <input name="invoice" value="${this.escape(record.invoice || "")}"></label><label>Invoice date <input name="invoiceDate" type="date" value="${record.invoiceDate || ""}"></label><label class="full">Update / Notes <textarea name="notes" rows="3" maxlength="300">${this.escape(record.notes || "")}</textarea></label></div><div class="modal-actions"><button type="button" class="button secondary" data-action="close-overlay">Cancel</button><button class="button primary" type="submit">Save record</button></div></form></div>`;
  }

  showBoardForm(board) { document.querySelector("#overlay-root").innerHTML = `<div class="overlay" data-action="close-overlay"><form class="modal small-modal" data-action="board-form"><div class="modal-head"><div><div class="eyebrow">Workspace board</div><h2>${board ? "Rename board" : "New board"}</h2></div><button type="button" class="icon-button" data-action="close-overlay">${icon("close")}</button></div><input type="hidden" name="id" value="${board?.id || ""}"><div class="form-grid"><label class="full">Board name <input name="name" required maxlength="60" value="${this.escape(board?.name || "")}" placeholder="Project tracker"></label></div><div class="modal-actions"><button type="button" class="button secondary" data-action="close-overlay">Cancel</button><button class="button primary">${board ? "Save name" : "Create board"}</button></div></form></div>`; }

  showWorkspaceMenu(model) { document.querySelector("#overlay-root").innerHTML = `<div class="popover workspace-popover">${model.workspaces.map((space) => `<button data-action="switch-workspace" data-id="${space.id}" class="${space.id === model.currentWorkspaceId ? "selected" : ""}"><span class="workspace-icon" style="background:${space.color}">${space.name[0]}</span><span><strong>${space.name}</strong><small>${space.boards.length} boards</small></span>${space.id === model.currentWorkspaceId ? "✓" : ""}</button>`).join("")}</div>`; }
  showBoardMenu(board) { document.querySelector("#overlay-root").innerHTML = `<div class="popover board-popover"><button data-action="rename-board" data-id="${board.id}">${icon("edit")} Rename</button><button data-action="duplicate-board" data-id="${board.id}">${icon("copy")} Duplicate</button><button class="danger" data-action="delete-board" data-id="${board.id}">${icon("trash")} Delete</button></div>`; }
  showMore() { document.querySelector("#overlay-root").innerHTML = `<div class="popover more-popover"><button data-action="global-search">${icon("search")} Search all boards</button><button data-action="settings">${icon("settings")} Workspace settings</button><button data-action="shortcuts">? Keyboard shortcuts</button></div>`; }
  showSettings(model) { document.querySelector("#overlay-root").innerHTML = `<div class="overlay drawer-overlay" data-action="close-overlay"><aside class="settings-drawer"><div class="modal-head"><div><div class="eyebrow">Medtek Database v7</div><h2>Settings</h2></div><button class="icon-button" data-action="close-overlay">${icon("close")}</button></div><section><h3>Theme</h3><div class="theme-grid">${["dark","light","teal","system"].map((theme) => `<button class="theme-option ${model.settings.theme === theme ? "selected" : ""}" data-action="theme" data-theme="${theme}"><span class="theme-preview ${theme}"><i></i><i></i><i></i></span><strong>${this.cap(theme)}</strong></button>`).join("")}</div></section><section><h3>Accessibility and display</h3><label class="setting-row"><span><strong>Accent color</strong><small>Personalize actions and focus states</small></span><input type="color" data-action="accent-color" value="${model.settings.accentColor}"></label><label class="setting-row"><span><strong>Text size</strong><small>Scale workspace interface text</small></span><select data-action="setting-select" data-key="fontSize">${["small","normal","large"].map((value)=>`<option ${model.settings.fontSize===value?"selected":""}>${this.cap(value)}</option>`).join("")}</select></label>${[["highContrast","High contrast","Strengthen borders and text"],["reduceMotion","Reduce motion","Disable interface animation"],["stickyFirstColumn","Sticky record column","Keep record names visible while scrolling"]].map(([key,label,help])=>`<label class="setting-row"><span><strong>${label}</strong><small>${help}</small></span><input type="checkbox" data-action="setting" data-key="${key}" ${model.settings[key]?"checked":""}></label>`).join("")}<label class="setting-row"><span><strong>Compact rows</strong><small>Fit more items on screen</small></span><input type="checkbox" data-action="density" ${model.settings.density === "compact" ? "checked" : ""}></label></section><section><h3>Data tools</h3><button class="button secondary wide-button" data-action="manage-columns">Configure columns and connections</button><button class="button secondary wide-button" data-action="export-backup">Export full JSON backup</button><p>Import accepts Medtek JSON backups, record JSON, and CSV files.</p></section></aside></div>`; }
  showInvite() { document.querySelector("#overlay-root").innerHTML = `<div class="overlay" data-action="close-overlay"><form class="modal small-modal" data-action="invite-form"><div class="modal-head"><div><div class="eyebrow">Local prototype</div><h2>Invite teammates</h2></div><button type="button" class="icon-button" data-action="close-overlay">${icon("close")}</button></div><div class="form-grid"><label class="full">Email addresses <textarea name="emails" rows="3" required placeholder="name@company.com"></textarea></label><label class="full">Role <select name="role"><option>Editor</option><option>Viewer</option></select></label></div><div class="notice">This standalone version demonstrates the invite workflow and does not send external email.</div><div class="modal-actions"><button type="button" class="button secondary" data-action="close-overlay">Cancel</button><button class="button primary">Create local invite</button></div></form></div>`; }
  showQuickChoice(title, options, action, id) { document.querySelector("#overlay-root").innerHTML = `<div class="overlay" data-action="close-overlay"><div class="modal small-modal"><div class="modal-head"><h2>${title}</h2><button class="icon-button" data-action="close-overlay">${icon("close")}</button></div><div class="choice-list">${options.map((value) => `<button data-action="${action}" data-id="${id}" data-value="${value}">${value}</button>`).join("")}</div></div></div>`; }
  showConfirm(title, text, action, payload = "") { document.querySelector("#overlay-root").innerHTML = `<div class="overlay" data-action="close-overlay"><div class="modal confirm-modal"><div class="confirm-icon">!</div><h2>${this.escape(title)}</h2><p>${this.escape(text)}</p><div class="modal-actions"><button class="button secondary" data-action="close-overlay">Cancel</button><button class="button danger-button" data-action="${action}" data-payload="${this.escape(payload)}">Confirm</button></div></div></div>`; }
  showMessage(title, text) { document.querySelector("#overlay-root").innerHTML = `<div class="overlay" data-action="close-overlay"><div class="modal confirm-modal"><div class="modal-head"><h2>${this.escape(title)}</h2><button class="icon-button" data-action="close-overlay">${icon("close")}</button></div><p>${this.escape(text).replaceAll("\n","<br>")}</p><div class="modal-actions"><button class="button primary" data-action="close-overlay">Done</button></div></div></div>`; }
  showGlobalSearch() { document.querySelector("#overlay-root").innerHTML = `<div class="overlay" data-action="close-overlay"><form class="modal small-modal" data-action="global-search-form"><div class="modal-head"><div><div class="eyebrow">Every workspace</div><h2>Search all boards</h2></div><button type="button" class="icon-button" data-action="close-overlay">${icon("close")}</button></div><div class="form-grid"><label class="full">Search term <input name="term" required autofocus placeholder="Serial, invoice, or note"></label></div><div class="modal-actions"><button type="button" class="button secondary" data-action="close-overlay">Cancel</button><button class="button primary">Search</button></div></form></div>`; }
  showGroupManager(model) { document.querySelector("#overlay-root").innerHTML = `<div class="overlay" data-action="close-overlay"><div class="modal small-modal"><div class="modal-head"><div><div class="eyebrow">Board structure</div><h2>Manage groups</h2></div><button class="icon-button" data-action="close-overlay">${icon("close")}</button></div><div class="manager-list">${model.board.groups.map((group) => `<div class="manager-row"><input data-role="group-name" data-old="${this.escape(group)}" value="${this.escape(group)}"><button data-action="save-group" data-old="${this.escape(group)}">Save</button><button class="danger" data-action="request-delete-group" data-group="${this.escape(group)}" ${model.board.groups.length === 1 ? "disabled" : ""}>Delete</button></div>`).join("")}</div><form class="inline-form" data-action="add-group-form"><input name="name" required placeholder="New group name"><button class="button primary">Add group</button></form></div></div>`; }
  showColumnManager(model) { document.querySelector("#overlay-root").innerHTML = `<div class="overlay" data-action="close-overlay"><form class="modal column-modal" data-action="column-form"><div class="modal-head"><div><div class="eyebrow">Integration-ready schema</div><h2>Columns and connections</h2><p>Each connector key is stored independently for future API mapping.</p></div><button type="button" class="icon-button" data-action="close-overlay">${icon("close")}</button></div><div class="column-list">${model.columnDefinitions.map((column) => { const config=model.board.columnConfig[column.key]; return `<div class="column-row" data-column-key="${column.key}"><label><input type="checkbox" name="visible-${column.key}" ${config.visible ? "checked" : ""}><span><strong>${column.label}</strong><small>${column.key} · ${column.type}</small></span></label><input name="connection-${column.key}" value="${this.escape(config.connection)}" placeholder="Future connector key / endpoint"></div>`; }).join("")}</div><div class="modal-actions"><button type="button" class="button secondary" data-action="close-overlay">Cancel</button><button class="button primary">Save columns</button></div></form></div>`; }
  showSavedViews(model) { document.querySelector("#overlay-root").innerHTML = `<div class="overlay" data-action="close-overlay"><div class="modal small-modal"><div class="modal-head"><div><div class="eyebrow">Reusable filters</div><h2>Saved views</h2></div><button class="icon-button" data-action="close-overlay">${icon("close")}</button></div><div class="manager-list">${model.board.savedViews.map((view) => `<div class="manager-row"><button class="view-name" data-action="apply-saved-view" data-id="${view.id}">${this.escape(view.name)}<small>${view.status} · ${view.grouped ? "Grouped" : "Table"}</small></button><button class="danger" data-action="delete-saved-view" data-id="${view.id}">Delete</button></div>`).join("") || '<p class="muted-copy">No saved views yet.</p>'}</div><form class="inline-form" data-action="save-view-form"><input name="name" required placeholder="Name current filters"><button class="button primary">Save current view</button></form></div></div>`; }
  showProfileMenu(model, auth) { const avatar=model.profile.avatar ? `<img src="${model.profile.avatar}" alt="">` : this.escape(model.profile.initials); document.querySelector("#overlay-root").innerHTML = `<div class="profile-popover"><div class="profile-summary"><span class="profile large" style="background:${model.profile.color}">${avatar}</span><div><strong>${this.escape(model.profile.name)}</strong><small>${this.escape(model.profile.role)}</small><em><i class="presence presence-${model.profile.presence.toLowerCase()}"></i>${model.profile.presence}</em></div></div><div class="session-summary"><span>Session active</span><strong>${auth.sessionMinutesRemaining} min remaining</strong></div><button data-action="profile-settings">${icon("settings")} Profile settings</button><div class="presence-picker"><span>Set status</span>${["Available","Busy","Focus","Offline"].map((value)=>`<button data-action="set-presence" data-value="${value}" class="${model.profile.presence===value?"active":""}"><i class="presence presence-${value.toLowerCase()}"></i>${value}</button>`).join("")}</div><button data-action="nav" data-screen="mywork">${icon("work")} My work</button><button data-action="notifications">♧ Notifications <small>${model.unreadCount}</small></button><div class="session-actions"><button data-action="lock-session">Lock workspace</button><button class="danger" data-action="request-logout">Sign out</button></div></div>`; }
  showProfileSettings(model) { const avatar=model.profile.avatar ? `<img src="${model.profile.avatar}" alt="">` : this.escape(model.profile.initials); document.querySelector("#overlay-root").innerHTML = `<div class="overlay drawer-overlay" data-action="close-overlay"><form class="settings-drawer" data-action="profile-form"><div class="modal-head"><div><div class="eyebrow">Personal account</div><h2>Profile</h2></div><button type="button" class="icon-button" data-action="close-overlay">${icon("close")}</button></div><section class="avatar-editor"><span class="profile xlarge" style="background:${model.profile.color}">${avatar}</span><div><button type="button" class="button secondary" data-action="choose-avatar">Upload photo</button>${model.profile.avatar?'<button type="button" class="text-danger" data-action="remove-avatar">Remove</button>':""}<small>PNG, JPG, or WebP up to 1 MB</small></div></section><section class="profile-fields"><label>Username-synced name<input name="name" readonly value="${this.escape(model.profile.name)}"></label><label>Email<input name="email" type="email" value="${this.escape(model.profile.email)}" placeholder="name@company.com"></label><label>Role<input name="role" value="${this.escape(model.profile.role)}"></label><label>Avatar color<input name="color" type="color" value="${model.profile.color}"></label><label>Start screen<select name="startScreen">${["Last opened board","Home","My work"].map((value)=>`<option ${model.profile.startScreen===value?"selected":""}>${value}</option>`).join("")}</select></label></section><div class="modal-actions"><button type="button" class="button secondary" data-action="close-overlay">Cancel</button><button class="button primary">Save profile</button></div></form></div>`; }
  showNotifications(model) { document.querySelector("#overlay-root").innerHTML = `<div class="overlay drawer-overlay" data-action="close-overlay"><aside class="settings-drawer notification-drawer"><div class="modal-head"><div><div class="eyebrow">Personal inbox</div><h2>Notifications</h2></div><button class="icon-button" data-action="close-overlay">${icon("close")}</button></div><div class="notification-actions"><button data-action="mark-notifications">Mark all read</button><button data-action="clear-notifications">Clear</button></div><div class="notification-list">${model.notifications.map((item)=>`<button class="notification-item ${item.read?"":"unread"}" data-action="open-notification" data-board="${item.boardId}" data-workspace="${item.workspaceId}"><i></i><span><strong>${this.escape(item.text)}</strong><small>${this.time(item.at)}</small></span></button>`).join("") || '<p class="muted-copy">You are all caught up.</p>'}</div></aside></div>`; }
  showCommandPalette(model) { document.querySelector("#overlay-root").innerHTML = `<div class="overlay command-overlay" data-action="close-overlay"><div class="modal command-modal"><div class="command-search">${icon("search")}<input data-action="command-search" placeholder="Type a command..." autofocus><kbd>Esc</kbd></div><div class="command-list">${[["home","Go to Home"],["mywork","Open My work"],["new-record","Create a record"],["new-board","Create a board"],["notifications","Open notifications"],["profile","Edit profile"],["settings","Open settings"]].map(([command,label])=>`<button data-action="run-command" data-command="${command}" data-label="${label.toLowerCase()}">${label}<span>↵</span></button>`).join("")}</div><small class="command-hint">Tip: press Ctrl+K from anywhere.</small></div></div>`; }
  showDescription(model) { document.querySelector("#overlay-root").innerHTML = `<div class="overlay" data-action="close-overlay"><form class="modal small-modal" data-action="description-form"><div class="modal-head"><div><div class="eyebrow">Board context</div><h2>Board description</h2></div><button type="button" class="icon-button" data-action="close-overlay">${icon("close")}</button></div><div class="form-grid"><label class="full">Description<textarea name="description" rows="4" maxlength="240" placeholder="What is this board used for?">${this.escape(model.board.description)}</textarea></label></div><div class="modal-actions"><button type="button" class="button secondary" data-action="close-overlay">Cancel</button><button class="button primary">Save description</button></div></form></div>`; }
  closeOverlay() { const root=document.querySelector("#overlay-root"); if(root) root.innerHTML = ""; }
  toast(message) { const toast = document.createElement("div"); toast.className="toast"; toast.textContent=message; document.querySelector("#toast-region")?.append(toast); if (!document.querySelector("#toast-region")) { const region=document.createElement("div"); region.id="toast-region"; region.className="toast-region"; document.body.append(region); region.append(toast); } setTimeout(()=>toast.remove(),2800); }
  date(value) { return value ? new Intl.DateTimeFormat("en",{month:"short",day:"numeric",year:"numeric"}).format(new Date(`${value}T00:00:00`)) : "-"; }
  time(value) { return new Intl.DateTimeFormat("en",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value)); }
  cap(value) { return value[0].toUpperCase()+value.slice(1); }
  escape(value) { return String(value).replace(/[&<>'"]/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char])); }
}
window.AppView = AppView;
